name: xi2p
version: master
summary: The Xi2p I2P Router Project
description: |
  Xi2p is a security-focused, community-driven C++ implementation of I2P

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  xi2p:
    command: xi2p-wrapper
    plugs: [network, network-bind]

parts:
  xi2p:
    source: .
    source-type: git
    plugin: make
    build-packages:
      - g++
      - cmake
      - libboost-all-dev
      - libssl-dev
      - libssl1.0.0
    artifacts:
      - build/xi2p
      - pkg/config
      - pkg/client
    organize:
      build/xi2p: bin/
      pkg/*: .
  wrapper:
    plugin: dump
    source: snap/
    stage: [xi2p-wrapper]
