#!/bin/sh

if [ ! -d "$SNAP_USER_DATA/.xi2p" ]; then
  mkdir $SNAP_USER_DATA/.xi2p/
  cp -R $SNAP/config $SNAP_USER_DATA/.xi2p/
  cp -R $SNAP/client $SNAP_USER_DATA/.xi2p/
fi

exec "$SNAP/bin/xi2p" "$@"
